version: "3"

services:
  app:
    build: .
    restart: always
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database/development:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: PC1112131415
      MYSQL_DATABASE: template_dev_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 102030
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
    depends_on:
      - database
networks:
  default:
    name: template-network
    driver: bridge
